name: Start Factorio Server

on:
  workflow_dispatch:
    user:
      - benchungiscool
      - dlaming

jobs:
  start:
    runs-on: ubuntu-latest

    steps:
      - name: Start docker service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/factorio
            docker-compose up -d
          
