name: Stop Factorio Server

on:
  workflow_dispatch:
    user:
      - benchungiscool
      - dlaming

jobs:
  stop:
    runs-on: ubuntu-latest

    steps:
      - name: Stop docker service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/factorio
            docker-compose down

  export_save:
    runs-on: ubuntu-latest

    steps:
      - name: Copy file to repo
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/factorio/saves
            cp origin.zip ~/projects/factorio-server/saves/

      - name: Push save to remote
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/projects/factorio-server/saves
            git add origin.zip
            git commit -m "AUTOMATED: Push save to repo"
            git push origin main
            rm origin.zip

          
